research_task:
  description: >
    1. Using the serper tool, find websites that list rental properties in {location}
    2. Gather the most relevant (3 at most) websites into a list.

  expected_output: >
    A list of websites that may be used to find properties for rent in {location}.

search_task:
  description: >
    1. Using the web scrape tool and the list of websites available, find properties for rent in {location}.
    2. Search only for properties that have {no_rooms} bedrooms.
    3. Search only for properties that cost between {budget_min} and {budget_max} dollars per month.
    4. Gather the information for suitable properties into a list.

  expected_output: >
    A list containing information about the most suitable rental properties, for example price, location, amenities.

aggregate_task:
  description: >
    1. Select the 5 best candidates for rental properties out of a list based on price, location and amenities.
    2. Convert the information within the list to presentable paragraphs describing each property in detail to give to the client.
  expected_output: >
    5 paragraphs, each describing a single property, containing information such as location, price and amenities to give to the client.
